name: Test Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install libsasl2-dev wkhtmltopdf
          python -m pip install --upgrade pip
          pip install cython
          pip install thriftpy
          pip install pandas==1.4.2 -i https://pypi.python.org/simple
          pip install -e .[hive,test]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest --html=pytest-results-${{ matrix.python-version }}.html --self-contained-html
        env:
          ROBOT_KEY: ${{ secrets.WORK_WEIXIN_ROBOT_KEY }}

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: pytest-results-${{ matrix.python-version }}.html
        if: ${{ always() }}
